SET TERM ^ ;

CREATE OR ALTER PROCEDURE CREATE_ULID
RETURNS (
    ULID VARCHAR(26)
)
AS
DECLARE VARIABLE ENCODING VARCHAR(32);
DECLARE VARIABLE ENCODED_RANDOM VARCHAR(16);
DECLARE VARIABLE ENCODED_TIME VARCHAR(10);
DECLARE VARIABLE UNIXTIME BIGINT;
DECLARE VARIABLE I INTEGER;
DECLARE VARIABLE RAND INTEGER;
DECLARE VARIABLE TIME_VAR BIGINT;
DECLARE VARIABLE M INTEGER;
BEGIN
    ENCODING = '0123456789ABCDEFGHJKMNPQRSTVWXYZ';
    
    -- Generate Encoded Random Part
    ENCODED_RANDOM = '';
    I = 1;
    WHILE (I <= 16) DO
    BEGIN
        RAND = CAST(FLOOR(31 * RAND()) AS INTEGER);
        ENCODED_RANDOM = ENCODED_RANDOM || SUBSTRING(ENCODING FROM RAND + 1 FOR 1);
        I = I + 1;
    END
    
    -- Generate Encoded Time Part
    UNIXTIME = CAST((CURRENT_TIMESTAMP - TIMESTAMP '1970-01-01 00:00:00') * 86400000 AS BIGINT);
    TIME_VAR = UNIXTIME;
    ENCODED_TIME = '';
    I = 1;
    WHILE (I <= 10) DO
    BEGIN
        M = MOD(TIME_VAR, 32);
        ENCODED_TIME = SUBSTRING(ENCODING FROM M + 1 FOR 1) || ENCODED_TIME;
        TIME_VAR = TIME_VAR / 32;
        I = I + 1;
    END
    
    ULID = ENCODED_TIME || ENCODED_RANDOM;
    SUSPEND;
END^

SET TERM ; ^

